### ISSUE TITLE
Auto publish to dockerhub on each release

### ISSUE THREAD

**Issue by tarkah** [taylorbourne/xteve_lazystream#23]
This would be a great thing to test Github Actions with! Have it publish to docker hub when you create a new release. Would also save you some headache :P

**Comment by taylorbourne** [comment]
I was just playing around with that actually.. Right now whenever I merge into `master` is auto-publishes, and I actually don't have the option to turn that off in Docker Hub. I remember when we initially set this up I saw something saying the paid tier of Docker Hub allows this type of thing? 

Correct me if I'm wrong because I'd love to automate some of this stuff haha

**Comment by tarkah** [comment]
Yeah, you can just turn off that integration from Docker Hub I'd imagine, then use this:

https://github.com/elgohr/Publish-Docker-Github-Action

The cool thing is it'll still keep `latest` up to date with master, but also publish tags based on your releases. Probably not necessary for this type of project, but a good practice to learn how to do!

**Comment by tarkah** [comment]
Or you can keep that on and use the link for just handling releases. Something like this should work?

```yml
on:    
  release:
      types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
```
